name: Flutter Tag Manual Build

on:
  workflow_dispatch:

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
      ref: ${{ github.ref_name}}
